-- Debait Club — Supabase/Postgres schema
-- Run in the Supabase SQL editor (or psql). Safe to re-run: tables, indexes and
-- policies are all created idempotently. The service role bypasses RLS for seeding.

-- ---------------------------------------------------------------- tables ---

create table if not exists public.profiles (
  id uuid primary key,
  username text unique not null,
  display_name text,
  bio text,
  avatar_url text,
  created_at timestamptz default now()
);

create table if not exists public.topics (
  id bigint primary key,
  proposition text not null,
  category text not null,
  context text,
  sources jsonb default '[]'::jsonb,
  topic_date date not null,
  is_featured boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.cases (
  id bigint generated by default as identity primary key,
  topic_id bigint references public.topics(id) on delete cascade,
  side text check (side in ('for', 'against')),
  author_id uuid references public.profiles(id) on delete set null,
  body text not null check (char_length(body) <= 1680),
  score int default 0,
  created_at timestamptz default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  case_id bigint references public.cases(id) on delete cascade,
  author_id uuid references public.profiles(id) on delete set null,
  parent_id bigint references public.comments(id) on delete cascade,
  body text not null,
  stance text check (stance in ('strongly_agree', 'agree', 'neutral', 'disagree', 'strongly_disagree')),
  score int default 0,
  created_at timestamptz default now()
);

create table if not exists public.votes (
  id bigint generated always as identity primary key,
  voter_id uuid references public.profiles(id) on delete cascade,
  target_type text check (target_type in ('case', 'comment')),
  target_id bigint not null,
  created_at timestamptz default now(),
  unique (voter_id, target_type, target_id)
);

create table if not exists public.reports (
  id bigint generated always as identity primary key,
  reporter_id uuid references public.profiles(id) on delete cascade,
  target_type text check (target_type in ('case', 'comment')),
  target_id bigint not null,
  reason text,
  status text default 'open',
  created_at timestamptz default now()
);

create table if not exists public.saved_items (
  id bigint generated always as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  target_type text check (target_type in ('case', 'comment')),
  target_id bigint not null,
  created_at timestamptz default now(),
  unique (user_id, target_type, target_id)
);

-- ---------------------------------------------------------------- indexes --

create index if not exists cases_topic_id_idx on public.cases (topic_id);
create index if not exists cases_author_id_idx on public.cases (author_id);
create index if not exists comments_case_id_idx on public.comments (case_id);
create index if not exists comments_author_id_idx on public.comments (author_id);
create index if not exists votes_target_idx on public.votes (target_type, target_id);
create index if not exists votes_voter_idx on public.votes (voter_id);
create index if not exists saved_items_user_idx on public.saved_items (user_id);
create index if not exists topics_date_idx on public.topics (topic_date desc, id desc);

-- -------------------------------------------------------------------- RLS ---

alter table public.profiles enable row level security;
alter table public.topics enable row level security;
alter table public.cases enable row level security;
alter table public.comments enable row level security;
alter table public.votes enable row level security;
alter table public.reports enable row level security;
alter table public.saved_items enable row level security;

-- Public read on everything.
drop policy if exists "public read" on public.profiles;
create policy "public read" on public.profiles for select using (true);
drop policy if exists "public read" on public.topics;
create policy "public read" on public.topics for select using (true);
drop policy if exists "public read" on public.cases;
create policy "public read" on public.cases for select using (true);
drop policy if exists "public read" on public.comments;
create policy "public read" on public.comments for select using (true);
drop policy if exists "public read" on public.votes;
create policy "public read" on public.votes for select using (true);
drop policy if exists "public read" on public.reports;
drop policy if exists "reporters read own reports" on public.reports;
create policy "reporters read own reports" on public.reports
  for select using (reporter_id = auth.uid());
drop policy if exists "public read" on public.saved_items;
drop policy if exists "users read own saved items" on public.saved_items;
create policy "users read own saved items" on public.saved_items
  for select using (user_id = auth.uid());

-- Profiles: a signed-in user can create and edit only their own row.
drop policy if exists "users manage own profile" on public.profiles;
create policy "users manage own profile" on public.profiles
  for all using (id = auth.uid()) with check (id = auth.uid());

-- Cases: authenticated users may post; authors may edit/delete their own.
drop policy if exists "authenticated post cases" on public.cases;
create policy "authenticated post cases" on public.cases
  for insert with check (auth.role() = 'authenticated' and author_id = auth.uid());
drop policy if exists "authors manage own cases" on public.cases;
create policy "authors manage own cases" on public.cases
  for update using (author_id = auth.uid()) with check (author_id = auth.uid());
drop policy if exists "authors delete own cases" on public.cases;
create policy "authors delete own cases" on public.cases
  for delete using (author_id = auth.uid());

-- Comments: same shape as cases.
drop policy if exists "authenticated post comments" on public.comments;
create policy "authenticated post comments" on public.comments
  for insert with check (auth.role() = 'authenticated' and author_id = auth.uid());
drop policy if exists "authors manage own comments" on public.comments;
create policy "authors manage own comments" on public.comments
  for update using (author_id = auth.uid()) with check (author_id = auth.uid());
drop policy if exists "authors delete own comments" on public.comments;
create policy "authors delete own comments" on public.comments
  for delete using (author_id = auth.uid());

-- Votes: authenticated users may cast; voters may retract only their own.
drop policy if exists "authenticated cast votes" on public.votes;
create policy "authenticated cast votes" on public.votes
  for insert with check (auth.role() = 'authenticated' and voter_id = auth.uid());
drop policy if exists "voters retract own votes" on public.votes;
create policy "voters retract own votes" on public.votes
  for delete using (voter_id = auth.uid());

-- Saved items: same shape as votes.
drop policy if exists "authenticated save items" on public.saved_items;
create policy "authenticated save items" on public.saved_items
  for insert with check (auth.role() = 'authenticated' and user_id = auth.uid());
drop policy if exists "users unsave own items" on public.saved_items;
create policy "users unsave own items" on public.saved_items
  for delete using (user_id = auth.uid());

-- Reports: authenticated users may file reports (moderation handled out of band).
drop policy if exists "authenticated file reports" on public.reports;
create policy "authenticated file reports" on public.reports
  for insert with check (auth.role() = 'authenticated' and reporter_id = auth.uid());
