insert into public.cases (id, topic_id, side, author_id, body, score, created_at, is_deleted)
values
(101212,1,'against','ee7943b4-bcd5-5197-8301-9a00258a076d','Here is what actually happens the day after this law passes: every influencer with a manager moves their retouched content to an account registered somewhere the law does not reach, or labels everything with a wink while the audience keeps scrolling. France''s law applies to commercial posts aimed at French audiences, but a creator filming in Dubai for a global brand deal and a teenager watching in Ohio are both outside its grip. [French economy ministry guidance](https://www.economie.gouv.fr/particuliers/influenceurs). The internet does not have jurisdictions the way a high street does. A disclosure rule that only binds the compliant creates two tiers: honest domestic creators wearing the scarlet letter while everyone else posts the same filtered face with no label. And the label itself becomes noise. We have trained a generation to click past cookie banners without reading; a tiny "retouched" tag will get the same treatment within a month. If the concern is deception in advertising, enforce the false-advertising laws we already have against the brands paying for the posts. Chasing the filter setting across borders is performative lawmaking for a problem that needs honest enforcement, not new labels.',25,'2026-09-24T15:46:00+00:00',false),
(101213,4,'against','6069f4d9-134d-5568-b84d-113b4781f21f','The stock market does not go up in a straight line, which is a problem when you tax gains that can vanish. Imagine taxing a founder''s portfolio at its 2021 peak, then watching it fall 40 percent in 2022: the government has collected cash on wealth that no longer exists, and now it owes refunds, or the taxpayer has paid real money for phantom gains. The Congressional Budget Office has repeatedly flagged how volatile capital-gains revenue already is; a tax on unrealized gains would multiply that instability. [CBO](https://www.cbo.gov/). States would face the same whiplash. And the cruelty lands in downturns: to pay the tax, investors must sell assets into a falling market, the exact fire sale that turns a correction into a crash. We would be building a tax code that forces selling at the bottom and rewards it at the top. That is not redistribution. It is a machine for manufacturing panics.',36,'2026-09-24T04:42:20+00:00',false),
(101214,4,'against','942c33a1-2c9c-5e93-8669-ab48e2e29eb3','A tax on holding appreciating assets is a subsidy for spending instead of building. If keeping shares in the company you founded means an annual bill for gains you have not received, the rational move is to sell early, diversify into yachts and real estate, or move the whole enterprise somewhere that does not punish ownership. Founders already relocate: when countries raise the price of building companies, the builders leave, and the jobs follow. Economists at the Tax Foundation have documented capital flight following European wealth taxes. [Tax Foundation](https://taxfoundation.org/). The deeper issue is what we are taxing: patience. The gains in question mostly come from holding productive assets for decades. Penalize that and you get more short-term trading, more consumption, and fewer people willing to tie their fortune to one company''s twenty-year bet. A tax code should reward building things that last. This one fines it.',11,'2026-09-26T15:41:08+00:00',false),
(101215,7,'for','fa765893-7275-5eea-a263-a68aacd27d16','Corporate fines are priced in; customer payments are not. When a data broker gets caught selling location histories, the penalty goes to the government and the company treats it as the cost of a profitable quarter. The users whose clinic visits were sold get a press release. A mandatory payment flips the incentive: every record collected becomes a potential liability owed to a real person, which makes the CFO ask whether hoarding location data is worth it. The [FTC''s Outlogic order](https://thehackernews.com/2024/01/ftc-bans-outlogic-x-mode-from-selling.html) banned sales and ordered deletion, but deletion after the sale is closing the barn door. Payment prices the harm at the point of collection, before the harm happens. Companies respond to liabilities on the balance sheet faster than to lectures in consent decrees. If we want less location harvesting, make each harvested record expensive.',34,'2026-09-24T04:40:19+00:00',false),
(101216,7,'for','59067b26-6ba1-5a41-8dab-c3e5c54f02f6','The reason location misuse keeps happening is that each victim''s harm is too small to sue over and too personal to ignore. No one hires a lawyer because a broker sold their grocery-store trips for fractions of a cent, so the broker keeps selling millions of them. This is the classic collective-action problem, and the law already solved it elsewhere: wage-and-hour statutes let workers recover small underpayments automatically because the legislature knew nobody sues over $40. Location privacy needs the same machinery. The Supreme Court recognized in Carpenter that movement records paint an intimate portrait of a life. [Oyez](https://www.oyez.org/cases/2017/16-402). A statutory payment turns millions of individually un-sueable violations into one enforceable obligation, which is the only scale that matches how the data was taken: in bulk, automatically, without asking. Individual lawsuits were never going to fix bulk surveillance. Aggregated payment can.',13,'2026-09-24T16:46:03+00:00',false),
(101217,10,'for','ee62124c-cc74-5017-95ab-98931ddf1d27','The Academy''s craft branches are not a minority to be accommodated; they are the majority of the membership. Editors, sound engineers, costume designers, cinematographers, and the rest of the below-the-line branches make up most of the roughly 10,000 voting members, yet the telecast treats their awards as expendable. [Academy](https://www.oscars.org/). A ceremony run by an institution of filmmakers that sidelines filmmakers is incoherent. Equal airtime is not charity toward the crafts. It is the membership seeing itself on stage. When the 2022 pre-taped categories drew guild fury, it was the institution''s own base objecting. [The Wrap](https://www.thewrap.com/iatse-president-oscars-categories-pretaped/). Give every branch its live moment and the show stops insulting the people who pay the dues.',45,'2026-09-26T06:36:05+00:00',false),
(101218,10,'for','cdfe4d09-7e8c-5048-8b2b-dc5da75e4ba5','There is a labor story here, not just an etiquette story. In 2021, IATSE members voted overwhelmingly to authorize a nationwide strike over brutal hours and working conditions, the kind of conditions created by the same industry the Oscars celebrate. [IATSE](https://www.iatse.net/). When the telecast then shunts craft categories off the air, it tells those workers their labor is good enough to build the movies but not to be seen accepting for them, right when public visibility matters most for their bargaining power. Awards are one of the few moments below-the-line workers get in front of a mass audience. Treat that as expendable and you weaken the public standing of the next contract fight. Equal airtime says the industry''s highest-profile night stands with the crews, not just the stars. That is worth more than any montage.',5,'2026-09-24T12:57:15+00:00',false),
(101219,10,'against','84b4e3c8-f09e-5d8e-9c4f-2f651dc913bb','The Oscars are a private television production, not a public utility. Telling its producers exactly how many minutes each award gets is a content mandate, and mandates do not stop where you want them to. Today it is equal minutes for craft categories; tomorrow it is mandated speech lengths, mandated presenter lineups, mandated montages. The guilds already have real leverage: collective bargaining, public pressure, and the 2022 backlash that forced the Academy to reverse course. [The Wrap](https://www.thewrap.com/iatse-president-oscars-categories-pretaped/). Use that leverage. But a rule dictating the rundown of a private broadcast substitutes regulation for negotiation, and it will be administered by people whose incentive is avoiding controversy, not honoring film. The craft categories deserve better advocates than a stopwatch.',38,'2026-09-25T09:17:48+00:00',false);
insert into public.cases (id, topic_id, side, author_id, body, score, created_at, is_deleted)
values
(101220,10,'against','047cbe92-c3ce-55af-8df7-5158dcf2abe9','Mandate equal minutes and watch what producers actually do with them. A rule that says every category gets identical live time does not say the time has to be good. The rational compliance move is dead air: longer walk-ups, filler clips, and rushed winners shoved into a slot the producers resent, which teaches the audience to associate craft categories with the boring part of the night. The 2022 experiment was unpopular, but at least it was honest about what producers value. [GamesRadar](https://www.gamesradar.com/oscars-2022-categories-cut-live-broadcast/). Forced equality breeds malicious compliance, and the people it is supposed to help end up with a longer, colder spotlight. If the goal is genuine respect for craftspeople, you cannot legislate it into a rundown. You get it from producers who want to celebrate the work, and from audiences given a reason to care.',23,'2026-09-26T13:21:01+00:00',false),
(101221,10,'against','f92083ca-72b7-5231-9c96-9d36d67345bb','Airtime is the cheapest thing the industry can give craftspeople, which is why it is what everyone argues about. What editors and grips actually need is money: better residuals, safer hours, on-screen credit that survives the streaming interface, and contracts that do not treat them as disposable. The 2021 IATSE strike authorization was about punishing work schedules, not about the Oscars rundown. [IATSE](https://www.iatse.net/). An equal-minutes rule lets the industry feel generous while changing nothing about anyone''s paycheck or working conditions. It is symbolism purchased at the expense of substance, and it gives executives a heartwarming talking point to deploy the next time the crews ask for real gains. Fight for the contract. The telecast will follow.',32,'2026-09-25T16:59:02+00:00',false),
(101222,13,'against','375c4023-e676-5d4a-8dec-b98c23b99351','My daughter uses her tablet to communicate. She is autistic, and the device is her voice: her AAC app, her visual schedules, the video calls with her speech therapist. A shared household blackout that treats every screen as entertainment would take her voice away for the sake of a rule. She is not an edge case. Millions of kids use devices for accessibility, anxiety management, and staying connected to support networks, and a one-size household rule cannot tell the difference between a lifeline and a distraction. The American Academy of Pediatrics recommends a family media plan built around each child''s needs, not a single curfew for the house. [AAP](https://www.aap.org/). Shared hours sound fair until you meet the family they silence. Build the plan around the kid, not the clock.',8,'2026-09-25T03:58:40+00:00',false),
(101223,13,'against','8e1ee936-3d62-57ca-973c-8572c907b23d','Teenagers with their own phones and data plans do not obey household blackouts; they evade them. Tell a sixteen-year-old the wifi dies at nine and you will get a kid on cellular data under the covers, lying about it the next morning. Congratulations: the rule designed to bring the family together just made your kid a better liar. The research on parental monitoring is consistent that trust and communication predict outcomes better than surveillance. Common Sense''s own data shows teens are ambivalent about social media already. [Common Sense Media](https://www.commonsensemedia.org/press-releases/two-years-into-the-pandemic-media-use-has-increased-17-among-tweens-and-teens). Work with that ambivalence: talk about what they see, model putting your own phone down, agree on sleep boundaries together. A blackout imposed from above skips the conversation and goes straight to the arms race. Parents lose arms races with teenagers. Every time.',30,'2026-09-25T16:24:04+00:00',false),
(101224,16,'against','4c972619-65e6-5a0b-be86-ef7edbf6c5ab','Treaties take a decade; technology takes eighteen months. The DSA was proposed in 2020 and its full obligations only bit in 2024, an eternity in AI years. [European Commission](https://commission.europa.eu/). A binding global tech treaty would be negotiated by diplomats, ratified by 190 parliaments, and arrive just in time to regulate the previous generation''s problems. Worse, it would lock in those answers: once a standard is international law, updating it requires another round of global consensus, which means the rules ossify while the technology sprints. Voluntary frameworks can be revised in a year. National regulators can move in months. A binding treaty is the slowest possible instrument aimed at the fastest-moving target, and its main achievement would be giving everyone the comforting illusion that the problem was handled.',21,'2026-09-24T08:25:51+00:00',false),
(101225,16,'against','3926cd25-c966-5c00-b2ed-ab5895c8a7f0','Who do you vote out when the global tech regulator gets it wrong? Binding international rules move decisions from elected parliaments to treaty bodies and expert committees, and there is no ballot box for those. A national regulator that overreaches can be hauled before a legislature, sued in domestic courts, or reversed after an election. A global enforcement body answers to no voters, which is fine for technical standards like aviation safety and dangerous for questions as political as speech, surveillance, and AI. The DSA works because the EU has a parliament, courts, and democratic legitimacy behind its fines. [EDAA](https://edaa.eu/digital-services-act/enforcement-and-penalties/). A global equivalent would have the fines without the legitimacy. When enforcement is detached from democratic accountability, the rules serve whoever captured the process. Keep the power where the voters are.',16,'2026-09-24T20:53:24+00:00',false),
(101226,19,'for','674378e4-21e4-53ab-b8cb-18f19d173808','U.S. Soccer''s equal deal worked because two strong players'' unions sat across the table. Most federations'' athletes have no union, no agents, and no leverage: a record bonus is whatever the federation announces, take it or leave it. Standardized bonuses protect exactly those athletes, the ones who cannot bargain. A published schedule says a record is worth the same whoever sets it, which matters most in programs where the women''s team has no collective agreement and no one to call. FIFA''s prize pools show the gap standardized bonuses would start to close: $110 million for the 2023 Women''s World Cup against $440 million for the men. [PFA](https://pfa.net.au/the-pfa-post/pfa-post-womens-world-cup-prize-money-explained/). Federations will always say the context differs. A standard says the achievement does not. The athletes with the least power should not depend on their federation''s generosity.',13,'2026-09-24T09:06:16+00:00',false),
(101227,22,'for','fd549dfd-4b57-5350-965e-35628bcdf570','Tipping is a lie about prices. The menu says $18, the bill says $24 after the expected 25 percent, and everyone pretends the meal costs what the menu claims. No other industry gets to advertise one price and socially coerce another at the register. All-in pricing is simply honesty: the number on the menu is the number you pay, and the restaurant, not the customer''s mood, is responsible for paying its staff. Diners say they like tipping because it feels like control, but it is control over someone else''s rent, exercised by strangers with biases the research keeps documenting. Put the labor cost in the price, pay the wage, and let the menu tell the truth. States without a tip credit still have thriving restaurant scenes, which proves the honest price works. [DOL](https://www.dol.gov/agencies/whd/fact-sheet/15-tipped-employees-under-the-flsa).',7,'2026-09-24T06:58:00+00:00',false);
insert into public.cases (id, topic_id, side, author_id, body, score, created_at, is_deleted)
values
(101228,22,'for','200faecf-d070-52c4-a7dc-a4afd92b3541','Ask any longtime server about the worst part of the job and it is not the slow Tuesdays. It is the customer who knows your income depends on his mood. The tipping system hands every diner leverage over the person serving them, and study after study has found that tipped workers, disproportionately women, face higher rates of sexual harassment because enduring it is part of the paycheck. The Restaurant Opportunities Centers United has documented this dynamic for years. [ROC United](https://rocunited.org/). A higher base wage does not end harassment, but it ends the economic hostage situation: a server who can afford to walk away from a table can afford to report the man at it. Nobody should have to smile through groping to make rent. Abolish the subminimum wage and take the customer''s thumb off the scale.',38,'2026-09-24T10:31:55+00:00',false),
(101229,22,'against','1968764f-9b9b-5968-9771-516f3f5b3ae8','Abolition assumes every restaurant is a busy bistro in a rich zip code. It is not. The diner in a small town, the taco truck, the pizza place near campus: these run on thin margins and customers who cannot absorb 25 percent price hikes. The $2.13 federal tipped wage plus tips is a compromise that lets a server in Mississippi earn a living wage on Friday nights while the menu stays affordable on Tuesdays. Impose a flat high base wage everywhere and the small-town spots cut staff first, because they cannot raise prices the way a Manhattan brasserie can. Even DC, which passed Initiative 82, has lived through repeal fights and phase-in battles that show how contested this is locally. [Ballotpedia](https://ballotpedia.org/Washington,_D.C.,_Initiative_82,_Tip_Credit_Elimination_Initiative_(2022)). Labor markets differ by place. Let cities and states set the terms that fit, instead of one national rule written for the coasts.',33,'2026-09-24T03:05:41+00:00',false),
(101230,25,'for','1c344a5e-6bb6-56ea-804e-24575be72ea6','The ads do not just normalize betting; they lie about it. "Risk-free bet" sounds like you cannot lose, but the fine print says you get site credit, not cash, and only after you stake real money first. Britain''s ad regulator has repeatedly banned "risk free" gambling language as misleading, because it is. [ASA](https://www.asa.org.uk/). During live games these promos air between plays to an audience that includes kids and people in recovery, selling a financial product with cartoon mascots. A whistle-to-whistle ban does not stop adults from betting. It stops the most manipulative pitch, the one aimed at impulse, from running during the highest-emotion moments of the week. Advertise on your own time, with honest terms. The game broadcast is not your casino floor.',7,'2026-09-25T05:25:51+00:00',false),
(101231,25,'for','36cfff0c-65b8-5120-a6ca-5a6638482165','The ads are changing what happens to the athletes. Bettors who lose money on a missed free throw now find players on social media and threaten them, and it is getting worse as betting goes mainstream. College athletes, unpaid and barely out of high school, get threats over point spreads, and the NCAA has publicly flagged gambler harassment of athletes as a growing problem. [NCAA](https://www.ncaa.org/). The broadcast ads feed this directly: they frame every play as a financial event, turning players into stock tickers in the minds of angry losers. A whistle-to-whistle ban will not end gambling or end cruelty, but it stops the league''s own airtime from teaching fans to watch athletes as investments. The players did not sign up to be someone''s parlay leg. Stop selling the audience that idea during the game.',17,'2026-09-24T20:18:25+00:00',false),
(101232,28,'against','07f9f315-a1d3-5796-87e9-7a8d490e2130','Employee status comes with a tax bill nobody mentions. Right now athletic scholarships are generally not treated as taxable income. The moment athletes become employees, the scholarship, the housing, the meal plan, the tutoring, all of it starts to look like compensation, and the IRS taxes compensation. A swimmer on a $60,000 scholarship could owe thousands in federal taxes on money she never saw, which is a strange way to help college athletes. The [IRS rules on scholarships](https://www.irs.gov/) already draw careful lines here, and employment blows past them. The stars with NIL millions can absorb it. The rower from Ohio cannot. Revenue sharing under the House settlement delivers money without reclassifying anyone. [NCAA](https://www.ncaa.org/). Employee status delivers a W-2 and a tax bill to the athletes it claims to rescue.',39,'2026-09-25T06:32:21+00:00',false),
(101233,28,'against','d02683a0-27ae-5adc-b36c-da89e6493481','Employees can be fired. That is the part nobody puts on the poster. The moment athletes become university employees, the four-year scholarship becomes an at-will job, and coaches gain the power every employer has: cut the underperformer. Today a school that pulls a scholarship for athletic reasons faces outrage and, in the Power conferences, rules guaranteeing multi-year aid. Make the player an employee and the third-string linebacker with a bad knee is a layoff, not a tragedy. The NLRB framework the Dartmouth players used is real labor law, with management rights included. [NLRB](https://www.nlrb.gov/). Athletes would gain bargaining rights and lose the paternalistic protections that currently keep them on scholarship when they stop producing. For the stars, that trade might pay. For the 98 percent who will never go pro, trading guaranteed aid for the right to be terminated is a catastrophic bargain.',37,'2026-09-24T07:21:15+00:00',false),
(101234,2,'for','648235a5-4b71-5a93-af6b-338753de5433','In March 2024, bird flu turned up in American dairy cattle for the first time ever, and within weeks a Texas farmworker caught it from infected cows. That had never happened before: a flu virus jumping from birds to cows to a person, in that order. The CDC''s own writeup calls it the first instance of likely mammal-to-human transmission for this virus. [CDC](https://stacks.cdc.gov/view/cdc/157118) Now picture where it happened. Not on a small family dairy. The outbreak ripped through industrial herds where thousands of genetically similar animals breathe the same air, because that is what a factory farm is: a casino floor for viral mutation, running 24 hours a day. Every epidemiologist will tell you pandemics come from crowded animals. We got a warning shot in 2024. A ten-year phaseout is not radical. Waiting for the mutation that spreads between people is.',20,'2026-09-24T13:15:46+00:00',false),
(101235,2,'for','0657764b-1115-533d-841e-3e79ce8f8bdf','I shrimp the Louisiana coast, and every summer I watch a dead zone bloom across the water where my father used to trawl. NOAA forecast it at nearly 5,800 square miles in 2024, roughly the size of Connecticut, and the 37-year average sits above 5,200. It is not a mystery what feeds it. Fertilizer and manure wash down the Mississippi from industrial farms across 22 states, algae explodes, and everything on the bottom suffocates. [NOAA via Phys.org](https://phys.org/news/2024-06-noaa-average-summer-dead-zone.html) The price of cheap bacon is measured in square miles of ocean where nothing can live. My catch has moved farther out every decade, burning more fuel to find shrimp that used to be at the dock. A ten-year phaseout of factory farming will not fix the Gulf overnight, but it is the first policy I have seen that treats the manure as the industry''s problem instead of mine.',22,'2026-09-25T17:45:53+00:00',false);
insert into public.cases (id, topic_id, side, author_id, body, score, created_at, is_deleted)
values
(101236,2,'for','2914ba68-d865-5196-ad0d-893256c22cc9','Factory farming is, by the numbers, the least efficient way humans have ever produced food. The landmark Poore and Nemecek analysis found that livestock takes up 83 percent of the world''s farmland while delivering just 18 percent of our calories. [Our World in Data](https://ourworldindata.org) Read that again. We cleared forests the size of continents to run a system that returns less than a fifth of the calories for more than four-fifths of the land. Every argument for keeping factory farms assumes we need them to feed 10 billion people. The data says the opposite: they are the bottleneck. A ten-year phaseout is not a sacrifice of food security. It is the largest land-efficiency program available to a crowded planet, and the only thing standing in its way is an industry that profits from the waste.',16,'2026-09-25T22:31:43+00:00',false),
(101237,5,'for','ee62124c-cc74-5017-95ab-98931ddf1d27','Asking nicely has failed, and we have the receipts. A Reviews.org survey found 88.8 percent of moviegoers admit to using or looking at their phones during a film at the theater, up from 34.6 percent the year before. [Reviews.org](https://www.reviews.org/mobile/2025-cell-phone-addiction/) Nearly nine in ten. At that point the glowing screen is not a few rude people. It is the culture, and culture does not change because a pre-show bumper asked politely. Phone-free as the default simply admits what the numbers already say: the honor system lost. Keep a few clearly marked phone-friendly screenings for anyone who needs a device, and let the other ninety percent of showtimes be the dark, unbroken room people actually paid for.',14,'2026-09-25T14:24:38+00:00',false),
(101238,5,'for','a5e48176-d13e-56cd-9d5d-bf0677be0202','My kids'' school locks phones in pouches every morning, and you know what happened? Nothing. They survived. UNESCO''s 2023 education report went further and called on countries to ban smartphones in schools outright, finding that even a phone sitting nearby drags down learning. [Teacher Magazine](https://www.teachermagazine.com/in_en/articles/unesco-calls-for-smartphone-ban-in-schools) If a fourteen-year-old can go seven hours without a screen, the rest of us can manage two. The pouch panic is mostly projection by adults who cannot imagine it. Kids already live this policy five days a week. Theaters making it the default would just extend the one part of the day young people already handle fine.',26,'2026-09-26T05:28:10+00:00',false),
(101239,5,'for','ea6f2988-62b9-5a2f-832e-de4b2a9ee8c6','Theaters already sell a dozen different versions of the same movie: sensory-friendly screenings, 21-plus shows, subtitled showings, IMAX, matinees. Nobody calls that discrimination. It is just programming for different needs, which is exactly what a phone-free default with phone-friendly exceptions would be. [AMC](https://www.amctheatres.com) already runs monthly sensory-friendly screenings for guests who need lower volume and lights up, proof that multiplexes can segment showtimes without drama. The phone is no different from volume or lighting: one more variable in the room. Set the default for immersion, label the exceptions clearly, and stop pretending every screening must be identical.',44,'2026-09-25T01:42:23+00:00',false),
(101240,5,'against','06ce25a4-efd8-5581-88f7-c154d4c5c6b6','The highest-grossing concert film in history made $261.6 million worldwide, and its screenings were the opposite of phone-free. Theaters encouraged fans to sing, dance, and film the whole thing, because the phone was part of the show. [InsideHook](https://www.insidehook.com/music/taylor-swift-eras-tour-box-office-record/amp) That is where the theatrical business is actually growing: event cinema, where the audience''s second screen is a feature, not a bug. A phone-free default tells the exact customers keeping theaters alive that their kind of fun is wrong. You want to lecture Gen Z about attention spans? They will just stay home, where the phone is welcome and the popcorn is cheap. Theaters do not have an attention problem. They have an arrogance problem.',5,'2026-09-24T04:48:11+00:00',false),
(101241,8,'for','d02683a0-27ae-5adc-b36c-da89e6493481','Want to know what a $5 billion corporate privacy fine buys? About a 1.8 percent stock bump. When the FTC announced its record Facebook settlement, the market added roughly $10.4 billion to the company''s value, more than covering the penalty. [TechSpot](https://www.techspot.com/community/topics/facebooks-5-billion-fine-adds-10-billion-to-companys-value.255319/) The fine was not a punishment. It was a rounding error with a press release. That is the entire case for personal accountability in one chart: as long as violations are priced into the stock, nothing changes. Put the directors'' own compensation and liability on the line for repeat failures, and watch how fast privacy gets a real budget.',45,'2026-09-24T07:34:38+00:00',false),
(101242,8,'for','bdf81fc3-ae3a-513e-bdfa-a64476184ad5','We already ran this experiment. The FTC''s 2019 Facebook order did not just fine the company. It required Mark Zuckerberg to personally certify, every quarter, that the company was complying with privacy rules. [FTC](https://www.ftc.gov) A named human being, signing his name, on the record. That is the model worth extending: not prison for every breach, but a personal signature on compliance, with personal consequences when the signature turns out to be fiction and the violations repeat. Boards approve risk memos the way people approve software updates, without reading them. A signature that can cost you changes what you read before you sign.',36,'2026-09-26T00:48:08+00:00',false),
(101243,8,'against','38fea548-c1e9-55cb-8386-000018da5b31','A data breach is a crime, and we are talking about fining the victim''s board of directors for getting robbed. The FBI''s 2023 Internet Crime Report logged 880,418 complaints and losses over $12.5 billion, up 22 percent in a year. [FBI](https://www.fbi.gov/contact-us/field-offices/sanfrancisco/news/fbi-releases-internet-crime-report) That is the scale of the adversary: organized criminals, ransomware gangs, state hackers. Now imagine telling a director she faces personal ruin because a ransomware crew outmaneuvered her security team. The perverse result is obvious. Companies will spend the security budget on lawyers instead, because the legal threat is the one with a name on it. Hunt the criminals. Stop billing their victims.',29,'2026-09-24T21:00:00+00:00',false);
insert into public.cases (id, topic_id, side, author_id, body, score, created_at, is_deleted)
values
(101244,11,'for','10625523-a431-5678-888f-8127f2e8c8eb','We already accept speed bumps for dangerous velocity. Stock exchanges halt trading market-wide when the S&P 500 drops 7, 13, or 20 percent in a day. Nobody calls circuit breakers censorship. They exist because everyone understands that panicked speed destroys value faster than deliberation can repair it. [NYSE](https://www.nyse.com) Viral outrage is the same physics applied to information: anger accelerates sharing past the point where accuracy can catch up. A prompt before sharing a red-hot unopened link is a circuit breaker for the feed. Markets get them because money is at stake. The public square deserves at least as much engineering as the stock ticker.',42,'2026-09-25T21:29:35+00:00',false),
(101245,11,'for','d4f6b8cb-344c-53ee-a8f4-06d41cc3e7e9','The strongest evidence for friction does not come from a lab. It comes from WhatsApp. When the company limited highly forwarded messages to one chat at a time, it reported a 70 percent drop in viral forwards worldwide. [Digital Trends](https://www.digitaltrends.com/social-media/whatsapp-effort-to-tackle-misinformation-bears-fruit/) Seventy percent, from one small design change, with no posts removed and no accounts banned. The outrage merchants will tell you friction is censorship. WhatsApp proved it is plumbing. Slow the pipes and the flood recedes. Every platform that refuses the same fix for its own feed is telling you the flood is the business model.',31,'2026-09-24T15:23:37+00:00',false),
(101246,14,'for','1bcf61ee-325a-573f-a2b9-0eee4134e83c','I teach tenth grade, and I can spot the kids drowning in their feeds by second period. The CDC''s 2023 youth survey found 40 percent of high school students felt persistently sad or hopeless. [CDC](https://www.cdc.gov) Those kids are not booking therapists. But they do show up for school health screenings, the same ones that already check vision, hearing, and scoliosis. Adding two questions about sleep, harassment, and compulsive use to a screening they already attend is the lowest-cost intervention in public health. We do not wait for teenagers to self-diagnose bad eyesight. We should not wait for them to self-diagnose a feed that is wrecking their sleep either.',11,'2026-09-24T12:19:46+00:00',false),
(101247,14,'for','0a22dbd8-46a4-530c-b190-4b50e52c4c6d','Right now digital well-being support is a luxury good. Wealthy parents hire therapists, buy parental-control suites, and send kids to expensive detox camps. Everyone else gets thoughts and prayers. That is exactly the gap public-health services exist to close. The Surgeon General issued a formal advisory on social media and youth mental health in 2023 because the harms were too widespread to leave to the private market. [HHS](https://www.hhs.gov) Making support routine, through schools and clinics, means a kid''s access to help stops depending on their parents'' income and tech savvy. Mental health care that only exists for the rich is not a system. It is a sorting mechanism.',33,'2026-09-25T23:48:31+00:00',false),
(101248,17,'for','fd549dfd-4b57-5350-965e-35628bcdf570','Promotion does not follow demand. It creates it. The 1999 Women''s World Cup final drew 90,185 people to the Rose Bowl, a record that stood for over two decades, because organizers promoted it like the major event it was. [FIFA](https://www.fifa.com) Nobody in 1999 argued that women''s soccer had earned that crowd through decades of TV ratings. They built the stage, marketed it relentlessly, and the audience showed up. Every sport''s popularity was manufactured by somebody''s decision to put it in prime time. Women''s cricket is not waiting for an audience to materialize. It is waiting for broadcasters to do the obvious.',43,'2026-09-24T04:11:56+00:00',false),
(101249,17,'for','15a00d1a-ffdb-5656-967f-d13c7d840734','I coach my daughter''s cricket team, and I watch girls quit every season. The Women''s Sports Foundation has found girls drop out of sports at twice the rate of boys by age fourteen, and the reason they give most is that they cannot see a future in it. [Women''s Sports Foundation](https://www.womenssportsfoundation.org) Prime-time promotion is how a milestone becomes a poster on a bedroom wall. A girl who watches a record chase live, under lights, with commentators losing their minds, does not need a lecture on equality. She needs a hero. Put the milestones where heroes are made.',7,'2026-09-25T13:11:27+00:00',false),
(101250,17,'against','a1c24624-7d07-5bf6-887f-5a373ba432f3','Prime-time slots are not empty shelves waiting for a good cause. They are contracted inventory. The IPL''s 2023-27 media rights sold for $6.2 billion, which means every evening slot in cricket''s biggest market already belongs to somebody, with lawyers attached. [Sportcal](https://www.sportcal.com/media/completed-ipl-2023-27-rights-auction-secures-record-6-2bn/) An equal-promotion mandate does not create airtime. It confiscates it, and the confiscation lands on whoever has the weaker contract, which is usually another sport that also needs the audience. This is the part the mandate never answers: whose prime time gets taken? Equal sounds noble until you have to name the loser.',30,'2026-09-25T01:31:50+00:00',false),
(101251,17,'against','316b2c63-026a-57e4-a6b2-87c91c1f15e5','Here is what actually filled the MCG: a Katy Perry concert, International Women''s Day, twenty-dollar tickets, and months of creative marketing by people who treated the final like an event instead of an obligation. [ICC](https://www.icc-cricket.com/news/katy-perry-set-to-roar-at-icc-womens-t20-world-cup-final-on-international-womens-day) The 86,174 record did not come from a rule. It came from imagination. Mandates produce compliance: a promo aired at the contractually minimum hour to a half-empty room. Creativity produces crowds. If you want more MCG nights, do not legislate equal promotion. Hire the marketers who pulled off the last one and get out of their way.',30,'2026-09-25T09:20:04+00:00',false);
insert into public.cases (id, topic_id, side, author_id, body, score, created_at, is_deleted)
values
(101252,17,'against','9452332e-b87a-548b-b5f8-588d7203f62e','Here is the trap inside the mandate. If networks are forced to put women''s cricket milestones in prime time and the ratings disappoint, those numbers become a weapon. Every executive who never wanted the slot will wave the overnights as proof the sport does not rate, and the next rights negotiation gets worse, not better. Television runs on ratings, and ratings set the ad rates that fund everything downstream. [ESPNcricinfo](https://www.espncricinfo.com) A mandate that manufactures a public failure metric does not help women''s cricket. It hands its skeptics a chart. Let the audience growth, which is real, earn the slots. Forced parity that flops is the cruelest outcome of all.',34,'2026-09-25T22:36:01+00:00',false),
(101253,20,'for','1bcf61ee-325a-573f-a2b9-0eee4134e83c','We have built this institution before. In 1954, countries that had recently been at war pooled money and scientists to create CERN, shared infrastructure for physics too expensive and too important for any one nation. [CERN](https://home.cern) Frontier AI evaluation is the same shape of problem: the compute costs billions, the expertise is scarce, and every country needs trustworthy answers about what these systems can do. A small international body running shared evaluations and incident reporting is CERN for the one technology that will define the century. We know how to do this. We just have to decide AI deserves the same seriousness we gave particle physics.',23,'2026-09-26T17:39:12+00:00',false),
(101254,20,'for','942c33a1-2c9c-5e93-8669-ab48e2e29eb3','The Biological Weapons Convention has no verification mechanism. None. Countries simply promise, and the treaty is widely considered toothless because of it. [UN](https://www.un.org) That is the precedent the AI debate should stare at. Everyone now proposing a purely advisory AI body is rebuilding the BWC''s central flaw on purpose: an institution that can watch but cannot check. The lesson of bioweapons is not that verification is hard. It is that skipping it guarantees irrelevance. If we create an international AI body, give it inspection authority over the largest training runs from day one, or admit we are building theater.',35,'2026-09-26T08:05:05+00:00',false),
(101255,23,'against','cebbe9ba-a65b-5f65-88ba-8ae68deae197','Adrien Brody won Best Actor after it emerged that AI had refined his Hungarian dialogue in The Brutalist, using voice-cloning tools to fix vowels the dialect coach could not. [eWeek](https://www.eweek.com/news/brutalist-movie-oscars-ai-david-cronenberg/) Sit with that. A performance that was literally part software took the industry''s highest acting honor. If AI-assisted performances are eligible, the line does not hold at a little polish. It ends at a fully synthetic Best Actor, applauded by a room of people whose jobs the same technology is eliminating. Awards are supposed to measure human craft. The moment the trophy can go to an algorithm''s vowels, the category is a costume contest for code.',33,'2026-09-26T02:02:11+00:00',false),
(101256,23,'against','c42de967-cec8-5e1a-a097-c28408dbe53d','The audience has already voted with its gut. Pew found 52 percent of Americans are more concerned than excited about AI in daily life, with excitement in the single digits. [Pew](https://www.pewresearch.org/short-reads/2026/08/18/young-adults-in-the-us-are-increasingly-wary-of-ai-concerned-it-will-take-jobs/) Now imagine the headline: an AI-generated film wins Best Picture. To half the country, that reads as Hollywood endorsing the exact thing they fear, handed a trophy by the industry most visibly threatened by it. The Oscars are already fighting for relevance with a shrinking audience. Crowning a machine''s movie would not look bold. It would look like the industry surrendering its last argument for why human art matters, on live television.',13,'2026-09-25T03:38:02+00:00',false),
(101257,26,'for','9c8d1b75-7cb3-5bd9-8763-b4e02517c298','The five-day week is not a law of nature. It is a 1938 compromise, set when the Fair Labor Standards Act drew the line at 40 hours. [DOL](https://www.dol.gov) Meanwhile the people doing the hardest jobs in the country, nurses, firefighters, cops, have worked compressed schedules for decades: three twelves, four tens, then real days off. Nobody tells an ER nurse the unit will collapse if she is not there Friday. Hospitals run fine. The office workers clinging to five days are defending a Depression-era habit, not a productivity finding. If shift workers can cover lives around the clock on compressed weeks, your marketing team can survive a Friday off.',5,'2026-09-24T17:03:04+00:00',false),
(101258,29,'for','0657764b-1115-533d-841e-3e79ce8f8bdf','Standard time is the honest time. Noon under standard time is when the sun is actually highest; daylight time is the one-hour lie we all agreed to tell. [timeanddate.com](https://www.timeanddate.com) If we are finally abolishing the switch, the only defensible choice is the time that matches the sky. Permanent daylight time would mean winter sunrises at 8:45 in some cities, sending kids to school in pitch dark for months. The sleep scientists are right about the mechanism even if you dislike their tone: morning light anchors the circadian clock. Keep the real noon. End the fiction.',44,'2026-09-25T16:00:17+00:00',false),
(101259,29,'for','b89e3151-b364-5fa5-b619-f5bf7196de27','I cared for my mother through dementia, and I can tell you what the clock changes do to a fragile mind. They detonate the routine. Meals, meds, sunlight, sleep, everything her remaining cognition clung to, shifted by an hour overnight. Caregiver groups warn that disrupted routines and early darkness worsen sundowning, the evening confusion and agitation that already makes nights brutal. [Alzheimer''s Association](https://www.alz.org) She did not understand why it was dark at dinner. She just knew something was wrong, and she was frightened. Multiply that by millions of families. Abolishing the switch is not about convenience. It is about not terrorizing the most vulnerable people in the country twice a year.',37,'2026-09-25T20:53:42+00:00',false);
insert into public.cases (id, topic_id, side, author_id, body, score, created_at, is_deleted)
values
(101260,3,'for','798e5773-da4e-531c-a9f3-cc9078ba9d82','In 2000, Florida''s presidential result came down to 537 votes while more than 600,000 Floridians with past convictions could not vote, a gap the Sentencing Project''s Locked Out report has documented as larger than the margin itself. That is not a thought experiment, it is the actual recent history of the state most associated with this debate. Disenfranchisement does not fall randomly either; it concentrates in the same communities whose votes are already hardest to cast. When the excluded population dwarfs the deciding margin, the law is not just punishing individuals, it is quietly editing the electorate. Automatic restoration would not guarantee any outcome, but it would stop the state from choosing its voters quite so aggressively. [Sentencing Project](https://www.sentencingproject.org/app/uploads/2024/03/Locked-Out-2022-Estimates-of-People-Denied-Voting.pdf)',45,'2026-09-25T13:16:19+00:00',false),
(101261,3,'for','38fea548-c1e9-55cb-8386-000018da5b31','These laws were not written for the reasons their defenders cite today. After Reconstruction, states like Mississippi rewrote their constitutions in 1890 to disenfranchise people for crimes the delegates openly associated with Black citizens, while leaving crimes associated with white citizens off the list. The Brennan Center has traced how that design spread, which is why the racial gaps in disenfranchisement today are a feature, not a bug. Defenders now talk about the seriousness of punishment, but the architecture was built to shrink the Black electorate, and it still does. A policy born as a tool of white supremacy does not become neutral with age. Automatic restoration would finally retire a mechanism whose original purpose we all claim to reject. [Brennan Center](https://www.brennancenter.org/)',40,'2026-09-24T22:23:51+00:00',false),
(101262,6,'against','d6de6e43-46e0-5c6a-8628-86b8664c1c4f','A privacy violation by one product should not be priced against revenue from businesses that had nothing to do with it. When Luxembourg fined Amazon 746 million euros in 2021, the figure was scaled to global turnover, which meant money from cloud computing, logistics, and retail on other continents all fed a penalty for targeted advertising practices. The GDPR enforcement tracker records it among the largest fines ever issued. That is not proportionality, it is guilt by conglomerate. A company organized as ten separate firms would pay a tenth of what an integrated one pays for the identical misconduct. Tying fines to worldwide revenue punishes corporate structure instead of the violation, and it hands regulators a number designed to impress journalists rather than fit the harm. [GDPR enforcement tracker](https://www.cms.law/en/pol/publication/gdpr-enforcement-tracker-report/numbers-and-figures)',37,'2026-09-24T09:40:31+00:00',false),
(101263,6,'against','4ff27a04-8893-56ed-becd-a17274f513be','If revenue-linked fines deterred, Meta would have stopped by now. The company has collected some of the largest GDPR penalties on record, including the 1.2 billion euro fine in 2023, and the violations kept coming, because for a firm of that size even a record fine is a quarterly event, not an existential one. The GDPR enforcement tracker shows the same names recurring, which is exactly what deterrence theory predicts when the punishment is certain but affordable: it becomes a line item. Meanwhile the headline numbers let politicians claim victory while the underlying data practices continue. A fine that does not change behavior is not a deterrent, it is a licensing fee with better PR. Real deterrence would mean structural remedies, like forced deletion or bans on processing, not a bigger number on the same invoice. [GDPR enforcement tracker](https://www.cms.law/en/pol/publication/gdpr-enforcement-tracker-report/numbers-and-figures)',8,'2026-09-26T04:19:00+00:00',false),
(101264,9,'for','b89e3151-b364-5fa5-b619-f5bf7196de27','Women are roughly half the population, according to the Census Bureau, yet flagship sports coverage treats their milestones as a specialty interest. That would be a defensible business call for a purely private outlet, but much of the sports media ecosystem runs on public goods: broadcast spectrum, public stadiums, public universities supplying the athletes. When a publicly resourced industry covers the achievements of half its public as an afterthought, that is a failure of the bargain, not just an editorial preference. Milestones are also the cheapest coverage to get right: they are scheduled, verifiable, and brief. Giving a record-breaking performance the same slot regardless of who set it costs nothing and signals that the audience includes everyone. [Census](https://www.census.gov)',12,'2026-09-24T15:56:33+00:00',false),
(101265,9,'for','fd549dfd-4b57-5350-965e-35628bcdf570','Watch what gets the lead segment on a slow sports day: a male quarterback''s 300th touchdown pass, a manager''s 1,000th win, a trade rumor. Then watch an actual world record in a women''s event land in the briefs. The gap is not about audience size, it is about what editors have been trained to treat as important. FIFA expanded the Women''s World Cup to 32 teams in 2023 because the game kept growing into bigger stages, yet coverage habits still act like women''s milestones are the undercard. The proposition asks for one consistent test: is this a genuine milestone? If yes, it leads, whoever set it. Anything else is editors grading achievements on a curve and calling it judgment. [FIFA](https://www.fifa.com)',7,'2026-09-26T07:34:46+00:00',false),
(101266,9,'against','bd3a82ec-f35e-53eb-8a7f-09fed77ac5f2','Milestones are not evenly distributed because the sports are not evenly sized. The NBA has 30 teams playing 82 games; the WNBA fields roughly half as many teams on a far shorter schedule, and most women''s leagues are younger and smaller than their men''s counterparts. Fewer teams and fewer games mean fewer records, fewer championships, fewer historic firsts. That is arithmetic, not bias. A prominence rule that ignores it would force editors to elevate routine women''s results above bigger men''s stories, and audiences notice when the lead story is not the biggest story. Coverage should track the scale of the sport. As women''s leagues grow, and they are growing, their milestones will earn bigger placement on merit. Mandating it in advance just manufactures the resentment the rule claims to fix. [WNBA](https://www.wnba.com)',20,'2026-09-24T13:57:05+00:00',false),
(101267,12,'against','cdfe4d09-7e8c-5048-8b2b-dc5da75e4ba5','The people writing this curriculum do not live where the students do. Pew''s teen surveys keep finding YouTube and TikTok at the top of what teenagers actually use, while the adults designing the lessons and the school boards approving them inhabit a different internet entirely. A unit built by people who learned about TikTok from a news segment will be outdated before it is printed and mocked the week it is taught. Teenagers can smell condescension about their platforms the way they smell a substitute teacher''s fear. The habits worth building, like noticing when an app is engineered to keep you scrolling, are learned from peers and from experience, not from a worksheet. If schools want credibility here, they should hire the students to teach it. [Pew](https://www.pewresearch.org/internet/2023/12/11/teens-social-media-and-technology-2023/)',28,'2026-09-26T01:41:09+00:00',false);
insert into public.cases (id, topic_id, side, author_id, body, score, created_at, is_deleted)
values
(101268,12,'against','7d76392f-0482-5082-ad2f-2b4b16a71d47','Before mandating a curriculum, read what the Surgeon General actually said. The 2023 advisory warned about risks but also acknowledged how much researchers still do not know, which is why it called for more study alongside its recommendations. Building a required course on an evidence base its own authors called incomplete means teaching certainties that do not exist yet, and teenagers are excellent at detecting when adults are bluffing. What happens in five years when the research overturns half the slides? The curriculum either calcifies into dogma or gets quietly rewritten, and either way the school has spent credibility it did not have to spend. Mandates should follow settled science, not precede it. Fund the research first, teach what it finds second. [EdSource on the advisory](https://edsource.org/updates/surgeon-general-warns-social-media-may-harm-youth)',15,'2026-09-25T01:30:25+00:00',false),
(101269,15,'for','118e83f6-0987-5b39-ae9e-644bee8e3ed6','Right now the burden of discovering ongoing abuse falls on the public, which is absurd. The FTC had to sue the data broker Kochava in 2022 for allegedly selling location data that tracked people to sensitive places like reproductive health clinics, and cases like that take years while the data keeps flowing. An automatic audit flips the burden to where it belongs: the company that broke the rules pays to prove it stopped. Without that, a violator''s promise to behave is worth exactly what its last promise was worth. Independent verification is the difference between a settlement and a press release. If a business cannot survive proving it deleted the data it was told to delete, it should not have been selling people''s movements in the first place. [FTC](https://www.ftc.gov/)',35,'2026-09-24T07:20:36+00:00',false),
(101270,15,'for','68098df9-84c5-5727-9f57-9bdf1a2e0371','Here is the part nobody prices correctly: audits are cheap and breaches are not. IBM''s annual breach report put the average cost of a data breach at $4.45 million in 2023, before counting the regulatory fallout, and location data is among the hardest kinds to contain once it spreads. An automatic audit is a modest, predictable compliance cost next to that kind of exposure. Companies already buy cyber insurance and run penetration tests for the same reason: verification is cheaper than disaster. Making audits automatic after a violation just extends that logic to the aftermath, turning ''trust us, we fixed it'' into something a board can actually rely on. The firms that complain loudest about audit costs are usually the ones whose internal controls needed the audit most. [IBM](https://www.ibm.com/security/data-breach)',13,'2026-09-26T06:57:37+00:00',false),
(101271,15,'for','459f6151-07cd-5131-9c93-abc4a8b14c09','Negotiated settlements have a recidivism problem. Look at the GDPR record: the same giant platforms appear in the enforcement tracker again and again, collecting record fines and then collecting more, because a one-time penalty, however large, is a moment while the business model is forever. An automatic audit tail changes the time horizon. It says the scrutiny does not end when the headlines fade, and every subsequent review is a chance to catch the quiet return to old practices. Companies respond to what is measured repeatedly, not to what is punished once. If twenty years of check-ins sounds long, consider how long the data lives: location histories do not expire, so neither should the verification that they were handled properly. [GDPR enforcement tracker](https://www.cms.law/en/pol/publication/gdpr-enforcement-tracker-report/numbers-and-figures)',20,'2026-09-25T19:04:35+00:00',false),
(101272,18,'for','3926cd25-c966-5c00-b2ed-ab5895c8a7f0','Every medal starts somewhere unglamorous: a community pool, a school track, a volunteer coach staying late. Team GB''s 65 medals at Paris 2024 were the visible tip of a pyramid built in local clubs that elite funding never touches. A medal-only formula slowly starves that base, and then everyone acts surprised when the pipeline narrows a decade later. Weighting participation growth equally is not charity to grassroots sport, it is maintenance on the machine that produces the medals. No base, no pyramid, no podium. Countries that treat community sport as infrastructure keep producing champions; countries that treat it as a luxury good end up buying their medals with ever more expensive elite programs. Fund the roots and the medals take care of themselves. [BBC Sport](https://www.bbc.com/sport)',32,'2026-09-24T16:26:49+00:00',false),
(101273,18,'for','aa41ea2e-1856-5bfc-9547-d56c2937181a','Follow the money to its source and the medal-only formula looks indefensible. UK Sport runs on National Lottery and taxpayer funding, which means the cleaner who buys a lottery ticket on Friday is financing the system. She will never be an Olympian. Her kids might play community football. A funding model that directs her money exclusively toward sports that might win medals, while the facilities her family uses crumble, is a transfer from the many to the few dressed up as national pride. Equal weight for participation growth is the least the funders are owed: public money should buy public benefit, measured in the communities that paid for it. Medals are lovely, but they are not a sufficient return on the public''s investment. [UK Sport](https://www.uksport.gov.uk/)',10,'2026-09-24T03:43:53+00:00',false),
(101274,21,'for','0a22dbd8-46a4-530c-b190-4b50e52c4c6d','Here is the number that ends the ''best system in the world'' talk: the Commonwealth Fund''s international comparisons rank the United States worst among high-income nations on maternal mortality, by a wide margin. We spend roughly twice what peer countries spend per person and mothers die at rates that would embarrass a developing nation. This is not about rare diseases or exotic treatments, it is about the most basic thing a health system does, keeping people alive through childbirth, and ours fails at it because access depends on coverage, coverage depends on employment, and employment is not a health plan. A universal system would not fix everything, but it would end the absurdity where your zip code and your job determine whether you survive having a baby. [Commonwealth Fund](https://www.commonwealthfund.org)',41,'2026-09-25T18:46:09+00:00',false),
(101275,24,'for','bdf81fc3-ae3a-513e-bdfa-a64476184ad5','The problem is not just misuse, it is presence. A 2017 study in the Journal of the Association for Consumer Research found that the mere presence of a smartphone, even face down and silent, reduced people''s available cognitive capacity on attention and memory tasks. The researchers called it ''brain drain'': part of your mind is busy not thinking about the phone. That finding detonates every compromise based on discipline, because it means the kid who never touches their phone during class is still paying a cognitive tax for having it in their pocket. Teachers cannot confiscate a tax. Only removing the device removes the drain. A ban is the only intervention that addresses the mechanism the research actually identified. [Journal of the Association for Consumer Research](https://www.journals.uchicago.edu/doi/10.1086/691462)',24,'2026-09-26T15:15:00+00:00',false);
insert into public.cases (id, topic_id, side, author_id, body, score, created_at, is_deleted)
values
(101276,24,'for','8e917d68-eb3d-5016-9083-cd441fe1b6b5','The strongest evidence for a ban comes from the London School of Economics, where researchers studied schools before and after phone bans and found test scores rose, with the biggest gains among the lowest-achieving students. That last detail is the whole argument: affluent kids have tutors, quiet bedrooms, and parents who enforce screen rules at home, while disadvantaged students get none of that backup. The classroom is the one place where the playing field can be leveled, but only if the distraction is actually removed rather than managed. Opponents call bans blunt, and they are, like a seatbelt is blunt. The students who need the protection most are the least able to protect themselves. A nationwide ban would do for attention what free school meals did for nutrition: guarantee the baseline for everyone. [LSE](https://www.lse.ac.uk)',32,'2026-09-25T01:21:27+00:00',false),
(101277,24,'for','942c33a1-2c9c-5e93-8669-ab48e2e29eb3','America is debating this like it is a radical experiment, but France banned phones in primary and middle schools back in 2018, and the sky did not fall. The Netherlands followed with its own classroom ban, and UNESCO called for restrictions worldwide the same year Florida acted. This is now the international norm, not a fringe idea, and every country that has done it reports the same pattern: teachers get their classrooms back, students talk to each other again, and the predicted catastrophe of unreachable children never materializes because schools still have office phones. The US loves to lecture other countries about education while trailing them on the obvious fixes. A nationwide ban would not be an experiment. It would be catching up. [BBC](https://www.bbc.com/news)',38,'2026-09-24T18:39:05+00:00',false),
(101278,27,'for','f1d74300-6314-519d-858e-21531de9e328','The most effective monopoly strategy of the last fifteen years was not crushing competitors, it was buying them as toddlers. Meta paid about $1 billion for Instagram in 2012 and $19 billion for WhatsApp in 2014, snuffing out two potential rivals before either could threaten the core business. The FTC''s 2020 antitrust suit argued exactly that and sought to unwind the deals, because everyone understood what had happened except, apparently, the regulators who approved the mergers at the time. This is why breakups have to be on the table: once a giant has absorbed its future competition, no amount of conduct rules recreates the rival that was never allowed to grow up. You cannot regulate your way back to a competitor that was purchased in its crib. Structural separation is the only remedy that matches the structural crime. [FTC](https://www.ftc.gov/)',42,'2026-09-24T07:48:32+00:00',false),
(101279,27,'for','0212097b-9c4d-5391-8547-7b543026d660','Everyone frames this as a consumer issue, but ask the workers. In 2010 the Justice Department caught Apple, Google, Adobe, Intel, and others in no-poach agreements that suppressed engineers'' wages across Silicon Valley, and the companies eventually paid $415 million to settle. That is what concentrated power does when nobody is watching: it does not just raise prices, it holds down paychecks. Consumers get free search while the people building the products get a rigged labor market, and no individual engineer can bargain against a cartel of the world''s richest companies. Breaking up concentrated employers restores the one thing workers cannot create for themselves: competing bidders for their labor. Antitrust was written for exactly this, and the workers deserve the protection as much as the shoppers. [DOJ](https://www.justice.gov/)',10,'2026-09-24T01:58:43+00:00',false);
insert into public.votes (voter_id, target_type, target_id, created_at)
select v.voter, 'case', c.id,
       cc.created_at + random() * (extract(epoch from (now() - cc.created_at)) * interval '1 second')
from (values
(101212,25),
(101213,36),
(101214,11),
(101215,34),
(101216,13),
(101217,45),
(101218,5),
(101219,38),
(101220,23),
(101221,32),
(101222,8),
(101223,30),
(101224,21),
(101225,16),
(101226,13),
(101227,7),
(101228,38),
(101229,33),
(101230,7),
(101231,17),
(101232,39),
(101233,37),
(101234,20),
(101235,22),
(101236,16),
(101237,14),
(101238,26),
(101239,44),
(101240,5),
(101241,45),
(101242,36),
(101243,29),
(101244,42),
(101245,31),
(101246,11),
(101247,33),
(101248,43),
(101249,7),
(101250,30),
(101251,30),
(101252,34),
(101253,23),
(101254,35),
(101255,33),
(101256,13),
(101257,5),
(101258,44),
(101259,37),
(101260,45),
(101261,40),
(101262,37),
(101263,8),
(101264,12),
(101265,7),
(101266,20),
(101267,28),
(101268,15),
(101269,35),
(101270,13),
(101271,20),
(101272,32),
(101273,10),
(101274,41),
(101275,24),
(101276,32),
(101277,38),
(101278,42),
(101279,10)
) as c(id, n)
join public.cases cc on cc.id = c.id
cross join lateral (
  select p.id as voter from public.profiles p
  where p.id != cc.author_id
  order by random() limit c.n
) v;
select setval(pg_get_serial_sequence('public.cases','id'), (select max(id) from public.cases));
select setval(pg_get_serial_sequence('public.votes','id'), (select max(id) from public.votes));
